language: python
sudo: false
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - "3.6"

install:
 - pip install flake8
 - pip install black

script:
 # Static analysis
 - flake8 .
 - black --check --diff .

matrix:
  fast_finish: true
